# Generated by Django 5.2.6 on 2025-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('email_public', models.EmailField(blank=True, max_length=254)),
                ('phone_public', models.CharField(blank=True, max_length=50)),
                ('bio_md', models.TextField(blank=True, help_text='Markdown supported')),
                ('resume_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name_plural': 'About me',
                'constraints': [models.UniqueConstraint(fields=('full_name',), name='unique_about_me')],
            },
        ),
    ]
