# Generated by Django 5.2.6 on 2025-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('Programming Language', 'Programming Language'), ('Framework', 'Framework'), ('API & Architecture', 'API & Architecture'), ('DevOps & Deployment', 'DevOps & Deployment'), ('Authentication & Security', 'Authentication & Security'), ('Cloud', 'Cloud'), ('Database', 'Database'), ('Tools', 'Tools'), ('Soft Skills', 'Soft Skills')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Icon class name (e.g., from Font Awesome)', max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
