# Generated by Django 5.2.6 on 2025-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text="Use '-' at the beginning of a line for bullet points. Example:\n- First item\n- Second item\n- Third item")),
                ('project_type', models.CharField(choices=[('Backend', 'Backend'), ('Cloud', 'Cloud Architecture')], max_length=20)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('architecture_diagram', models.ImageField(blank=True, null=True, upload_to='architecture_diagrams/')),
                ('featured', models.BooleanField(default=False)),
                ('technologies_used', models.ManyToManyField(blank=True, related_name='projects', to='skills.skill')),
            ],
            options={
                'ordering': ['-featured', '-created'],
            },
        ),
    ]
