# Generated by Django 5.2.4 on 2025-09-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full-stack', 'Full-stack'), ('Cloud', 'Cloud Architecture')], max_length=20),
        ),
    ]
