# Generated by Django 5.2.4 on 2025-09-29 15:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='architecture_diagram',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
